name: Mavuno Berlin
email: info@mavuno.de
seo_title: Mavuno Berlin - EFG Lichterfelde K.d.ö.R.
meta_keywords: "sonntag, church, kirche, efg, efg lichterfelde, lichterfelde, walter-linse-strasse, osteweg, mavuno, berlin, mavuno berlin, zehlendorf, billy wilder promenade, mcnair, goerzallee, monroe park, freikirche, evangelisch, freikirchlich, protestantisch, green lofts, süden, gemeinde, jesus, bibel, beten"
meta_description: "Evangelisch Freikirchliche Gemeinde Lichterfelde Berlin K.d.ö.R."
timezone: Berlin
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mavuno.de" # the base hostname & protocol for your site, e.g. http://example.com
# paginate: 6
# permalink: "/:categories/:title/"

include:
  - _redirects

# collections:
#   some_collection:
#     output: true

# defaults:
#   - scope:
#       type: some_collections
#     values:
#       layout: some_collection_layout

# Build settings
markdown: kramdown
theme: theme-mavuno
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
