title: Mavuno Berlin
email: info@mavuno.de
description: Mavuno Berlin ist eine generationsübergreifende, multikulturelle Kirche, in der du Gott begegnest, die dir hilft, dein Potential zu entfalten und in der du gute Freunde findest.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mavuno.de" # the base hostname & protocol for your site, e.g. http://example.com
# paginate: 6
# permalink: "/:categories/:title/"

# collections:
#   some_collection:
#     output: true

# defaults:
#   - scope:
#       type: some_collections
#     values:
#       layout: some_collection_layout

# Build settings
markdown: kramdown
theme: theme-mavuno
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-assets
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
